// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNa_qicfRSuibVANjsIj6BsYGJVV8haQ0',
    appId: '1:133687474742:web:368e0aedd0c47e66eaf697',
    messagingSenderId: '133687474742',
    projectId: 'noryapp-2831b',
    authDomain: 'noryapp-2831b.firebaseapp.com',
    storageBucket: 'noryapp-2831b.firebasestorage.app',
    measurementId: 'G-JQDJGY68NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMG_oQtZx8HVFDp7RZM0JoWgbqaAdgcw',
    appId: '1:133687474742:android:de8725c5b1c123c9eaf697',
    messagingSenderId: '133687474742',
    projectId: 'noryapp-2831b',
    storageBucket: 'noryapp-2831b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXfpQWiO6eqY_Z4-AzMTXjXy9M-33qpk',
    appId: '1:133687474742:ios:2b18c14c6ade5023eaf697',
    messagingSenderId: '133687474742',
    projectId: 'noryapp-2831b',
    storageBucket: 'noryapp-2831b.firebasestorage.app',
    iosClientId: '133687474742-l4tdlb7iqb1kkh65o0vjbaco4ttkh9eh.apps.googleusercontent.com',
    iosBundleId: 'com.smartfood.smartFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXfpQWiO6eqY_Z4-AzMTXjXy9M-33qpk',
    appId: '1:133687474742:ios:2b18c14c6ade5023eaf697',
    messagingSenderId: '133687474742',
    projectId: 'noryapp-2831b',
    storageBucket: 'noryapp-2831b.firebasestorage.app',
    iosClientId:
        '133687474742-l4tdlb7iqb1kkh65o0vjbaco4ttkh9eh.apps.googleusercontent.com',
    iosBundleId: 'com.smartfood.smartFood',
  );

}